import { Controller } from "@hotwired/stimulus";

export default class extends Controller {
  static targets = ["tooltip"];

  open(event) {
    event.stopPropagation();
    this.contentTarget.innerHTML = this.sourceTarget.innerHTML;
    this.modalTarget.classList.remove("hidden");
  }

  close(event) {
    event.stopPropagation();
    this.modalTarget.classList.add("hidden");
    this.contentTarget.innerHTML = "";
  }

  stopPropagation(event) {
    event.stopPropagation();
  }

  async copyPng(event) {
    const button = event.currentTarget;

    const flexCol = button.closest(".flex.flex-col");
    let svg = null;
    if (flexCol) {
      const diagramSource = flexCol.querySelector(
        '[data-diagram-modal-target="source"]',
      );
      if (diagramSource) {
        svg = diagramSource.querySelector("svg");
      }
    }
    if (!svg) {
      alert("SVG not found");
      return;
    }

    const svgClone = svg.cloneNode(true);
    const style = document.createElement("style");
    style.textContent = `
      svg.railroad-diagram { background-color: hsl(30, 20%, 95%); }
      svg.railroad-diagram path { stroke-width: 3; stroke: black; fill: rgba(0,0,0,0); }
      svg.railroad-diagram text { font: bold 14px monospace; text-anchor: middle; }
      svg.railroad-diagram text.label { text-anchor: start; }
      svg.railroad-diagram text.comment { font: italic 12px monospace; }
      svg.railroad-diagram rect { stroke-width: 3; stroke: black; fill: hsl(120, 100%, 90%); }
      svg.railroad-diagram rect.group-box { stroke: gray; stroke-dasharray: 10 5; fill: none; }
    `;
    svgClone.insertBefore(style, svgClone.firstChild);

    const pattern = button.getAttribute("data-pattern") || "";
    if (pattern) {
      const labelText = `Regex: ${pattern}`;

      const svgWidth =
        svgClone.getAttribute("width") ||
        svgClone.viewBox?.baseVal?.width ||
        600;

      const g = document.createElementNS("http://www.w3.org/2000/svg", "g");
      while (svgClone.childNodes.length > 0) {
        g.appendChild(svgClone.childNodes[0]);
      }
      svgClone.appendChild(g);

      const text = document.createElementNS(
        "http://www.w3.org/2000/svg",
        "text",
      );
      text.setAttribute("x", svgWidth / 2);
      text.setAttribute("y", 28);
      text.setAttribute("font-size", "18");
      text.setAttribute("font-family", "monospace");
      text.setAttribute("font-weight", "bold");
      text.setAttribute("fill", "#333");
      text.textContent = labelText;
      svgClone.insertBefore(text, g);

      const origHeight =
        parseFloat(svgClone.getAttribute("height")) ||
        svgClone.viewBox?.baseVal?.height ||
        100;
      svgClone.setAttribute("height", origHeight + 64); // 32 for top, 32 for footer
      if (svgClone.hasAttribute("viewBox")) {
        const vb = svgClone.getAttribute("viewBox").split(" ").map(Number);
        if (vb.length === 4) {
          vb[3] += 64;
          svgClone.setAttribute("viewBox", vb.join(" "));
        }
      }
      g.setAttribute("transform", "translate(0,32)");

      const footer = document.createElementNS(
        "http://www.w3.org/2000/svg",
        "text",
      );
      footer.setAttribute("x", svgWidth / 2);
      footer.setAttribute("y", origHeight + 48); // Place it 16px below original bottom
      footer.setAttribute("font-size", "10");
      footer.setAttribute("font-family", "monospace");
      footer.setAttribute("fill", "#666");
      footer.textContent = "Generated by Rubree";
      svgClone.appendChild(footer);
    }

    const svgData = new XMLSerializer().serializeToString(svgClone);
    const svgBlob = new Blob([svgData], { type: "image/svg+xml" });
    const url = URL.createObjectURL(svgBlob);
    const img = new window.Image();

    img.onload = async () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext("2d");
      ctx.drawImage(img, 0, 0);

      canvas.toBlob(async (blob) => {
        try {
          await navigator.clipboard.write([
            new window.ClipboardItem({ "image/png": blob }),
          ]);
          const tooltip = button.querySelector(
            '[data-diagram-clipboard-target="tooltip"]',
          );
          if (tooltip) {
            tooltip.classList.remove("opacity-0", "invisible");
            setTimeout(
              () => tooltip.classList.add("opacity-0", "invisible"),
              1000,
            );
          }
        } catch (e) {
          alert(`Failed to copy PNG to clipboard: ${e}`);
        }
      }, "image/png");

      URL.revokeObjectURL(url);
    };

    img.onerror = () => {
      alert("Failed to load SVG image");
      URL.revokeObjectURL(url);
    };

    img.src = url;
  }
}
