// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import RegexpContentTabSwitchController from "./regexp_content_tab_switch_controller";

application.register(
  "regexp-content-tab-switch",
  RegexpContentTabSwitchController,
);

import RegexpExamplesController from "./regexp_examples_controller";

application.register("regexp-examples", RegexpExamplesController);

import RegexpFormController from "./regexp_form_controller";

application.register("regexp-form", RegexpFormController);
