// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import CopyCodeController from "./copy_code_controller";

application.register("copy-code", CopyCodeController);

import DiagramModalController from "./diagram_modal_controller";

application.register("diagram-modal", DiagramModalController);

import DragScrollController from "./drag_scroll_controller";

application.register("drag-scroll", DragScrollController);

import RegexpContentTabSwitchController from "./regexp_content_tab_switch_controller";

application.register(
  "regexp-content-tab-switch",
  RegexpContentTabSwitchController,
);

import RegexpExamplesController from "./regexp_examples_controller";

application.register("regexp-examples", RegexpExamplesController);

import RegexpFormController from "./regexp_form_controller";

application.register("regexp-form", RegexpFormController);
