plugins:
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-capybara

# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  NewCops: enable
  Exclude:
    - "build/**/*"
    - "rubies/**/*"
    - "pwa/**/*"

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
