name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  lint_ruby:
    name: Lint Ruby
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: RuboCop
        run: bin/rubocop -f github

      - name: ERB Lint
        run: bin/erb_lint --lint-all

  lint_frontend:
    name: Lint Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: ./.node-version
          cache: yarn
          cache-dependency-path: ./yarn.lock

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
        
      - name: Run Biome
        run: biome ci app/assets/stylesheets app/javascript app/views

  secret_scan:
    name: Secret Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Run Gitleaks
        run: |
          docker run --rm -v "$(pwd):$(pwd)" -w "$(pwd)" \
          zricethezav/gitleaks detect --source="$(pwd)" --verbose --redact \
          --log-opts="--all --full-history"
          
  sast:
    name: SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Run Brakeman
        run: bin/brakeman --no-pager --skip-files app/assets/builds/,build/,node_modules/,pwa/,rubies/

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: ./.node-version
          cache: yarn
          cache-dependency-path: ./yarn.lock

      - name: Install dependencies for Playwright WebKit
        run: |
          sudo apt-get update
          sudo apt-get install -y libwoff2-1 libatk-bridge2.0-0 libgtk-3-0 libxss1 libnss3 libasound2

      - name: Extract Playwright version
        id: playwright-version
        run: echo "version=$(jq -r '.devDependencies.playwright' package.json)" >> "$GITHUB_OUTPUT"
      
      - name: Cache Playwright Browsers
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}
          restore-keys: |
            ${{ runner.os }}-playwright-

      - name: Install JS dependencies
        run: yarn install --frozen-lockfile

      - name: Install playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Build frontend assets
        run: yarn build

      - name: Run system specs with Playwright (Chromium Headless)
        run: |
          echo "Running with DRIVER=playwright_chromium_headless"
          DRIVER=playwright_chromium_headless bin/rspec

      - name: Run system specs with Playwright (Firefox Headless)
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Running with DRIVER=playwright_firefox_headless"
          DRIVER=playwright_firefox_headless bin/rspec

      - name: Run system specs with Playwright (WebKit Headless)
        # if: github.ref == 'refs/heads/main' # debug
        run: |
          echo "Running with DRIVER=playwright_webkit_headless"
          DRIVER=playwright_webkit_headless bin/rspec

      - name: Run system specs with Selenium (Chrome Headless)
        # if: github.ref == 'refs/heads/main' # debug
        run: |
          echo "Running with DRIVER=selenium_chrome_headless"
          DRIVER=selenium_chrome_headless bin/rspec
